# Generated by Django 2.2.18 on 2021-03-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210302_2208'),
        ('mainapp', '0002_auto_20210303_1124'),
    ]

    operations = [
    ]
