# Generated by Django 2.2.18 on 2021-04-06 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20210406_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='aboutMe',
            new_name='about_me',
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 7, 56, 22, 446198, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('W', 'Ж')], max_length=128, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=128, verbose_name='тэги'),
        ),
    ]
