# Generated by Django 3.1.7 on 2021-04-22 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20210420_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 7, 43, 24, 780272, tzinfo=utc)),
        ),
    ]
